### ISSUE TITLE
BUG: Execution of ./exe.sh local_obj.json throws error.

### ISSUE THREAD

**Issue by TeaBizzy** [jacobkim9881/localization-manager#11]
When I run command `./exe.sh local_obj.json` the program executes, but no output files are generated and I receive error for each language it tries to translate:
`./exe.sh: line 37: /usr/bin/expect: No such file or directory`

What I think is happening is `./exe.sh` is looking for that specific directory to create the translated files in, but this repo doesn't contain that directory.

If my assumption is correct, we should change the output location to a directory within this repo to prevent this error.

@jacobkim9881 please let me know if this is correct, or if the error is on my end.

Steps to reproduce:
1. Fork repo.
2. Clone repo.
3. Navigate to the repo in terminal.
4. Run command: ./exe.sh local_obj.json

_Screenshot of the error:_
![Screenshot from 2022-09-23 09-39-52](https://user-images.githubusercontent.com/111951212/191973263-a11ac7db-3010-4292-890e-25537a35c0ae.png)

**Comment by jacobkim9881** [comment]
At line 37 in `exe.sh`

```
 do /usr/bin/expect <<- EOF
```

Seems the machine didn't find any files to execute. The only command to execute is ` spawn node ./src/index.js $num $var`. 

Currently `./exe.sh` finds json files in `./` if a user didn't give specific path for the json file. If a user has bunch of json files to translate then putting the target files in `./` directory which has `package.json` file, execution file `exe.sh` the user has an issue for finding his/her target file. 

There was no error in `master` branch in my end. Can I know which branch has the error?

**Comment by TeaBizzy** [comment]
@jacobkim9881 I'm on the master branch. I checked the `./src/` directory and it has the `index.js` file. Are the finished translated files created in `/usr/bin/expect`?

**Comment by jacobkim9881** [comment]
Then on your end the `master` branch is not updated to lastest. Have you command `git fetch` at `./`? It may update commits you didn't get. Is `local.json` file put at `./`?
`/usr/bin/expect` is where `expect` linux app is.

**Comment by jacobkim9881** [comment]
Am sorry. Seems I didn't update the `master` branch. Let me push the commits.

**Comment by jacobkim9881** [comment]
Can you try `git fetch` and pull `master-temp` branch by `git pull <master origin remote> master-temp`? I updated master branch and pushed into temporary branch.

**Comment by TeaBizzy** [comment]
So I did a bit of googling. I wasn't aware expect needs to be installed.

I have now installed expect and tried again, but now I get error: Error: Cannot find module 'translate-google'
![Screenshot from 2022-09-23 11-52-18](https://user-images.githubusercontent.com/111951212/192001910-d212c249-5405-4c71-b003-f042738cffd3.png)

I'm guessing I also need to install this. I will try and see if I can get it to work. However I recommend adding these requirements to the `readme.me`

**Comment by TeaBizzy** [comment]
Not sure if this was the right package. But after installing [this](https://snapcraft.io/install/google-translate/ubuntu). I still get the same error.

**Comment by jacobkim9881** [comment]
`translate-google` is nodejs package. Seems your node_module folder is deleted. `npm install` at `./` will install the module.

**Comment by jacobkim9881** [comment]
> So I did a bit of googling. I wasn't aware expect needs to be installed.

I also thought expect is pre-installed. I should test what error message occurs without installing expect.

**Comment by TeaBizzy** [comment]
@jacobkim9881 that did the trick :heart:
