### ISSUE TITLE
Too long to read for a variable

### ISSUE THREAD

**Issue by jacobkim9881** [jacobkim9881/localization-manager#3]
### Briefing
Variable and parameter names of recusion function are too long to read and the names should be edited into shorter and more readable name. 

### Problem
The variable and parameter names `arrayOfStringsWithTagPath` at line 26 `./src/index.js` and at `addStr` function in `./src/utils.js` are too long to read. 

### Objective
The variable and parameter names `arrayOfStringsWithTagPath` should have shorter and more readable name.

### What is a role the variable
This repo changes `.json` files into translated `.json` files by helping Google translate API(If you want to how the repository works then go to [README.md](https://github.com/jacobkim9881/localization-manager#briefing-about-how-the-program-works). To translate the `.json` file every keys and values of the json file should be parsed by recursion. After recursion function, each key path from the root key is pushed into an array `arrayOfStringsWithTagPath`. So the output array of the recursion function is `arrayOfStringsWithTagPath`. This variable is put into `addStr` function and repeated by recursion. 

### To do
- Fork this repository of `refact` branch.
- Install npm modules at your fork.
- Edit variable name `arrayOfStringsWithTagPath` at line 26 `./src/index.js` 
- Edit parameter name `arrayOfStringsWithTagPath` and at `addStr` function in `./src/utils.js`
- Test if the fork is working by executing `./exe.sh local_obj.json` at `./`.
- If error occurs fix.
- If no error ask pull request.

**Comment by Niravprajapati1** [comment]
Can you suggest a variable name ?

**Comment by jacobkim9881** [comment]
@Niravprajapati1 It may be name with tag path. The keys in `local_obj.json` has tag paths.

**Comment by Niravprajapati1** [comment]
> 
Can you share some examples?

**Comment by jacobkim9881** [comment]
@Niravprajapati1 I am sorry the issue is solved and closed before giving you any guidance. There is [other issue](https://github.com/jacobkim9881/localization-manager/issues/10) and could you give any advice or take the issue to solve?

**Comment by Niravprajapati1** [comment]
@jacobkim9881 sure 😁
