### ISSUE TITLE
Document guides will not in no use after #7 pulled into 

### ISSUE THREAD

**Issue by jacobkim9881** [jacobkim9881/localization-manager#9]
By #7 the document guides ([the first](https://github.com/jacobkim9881/localization-manager#localization-manager), [the second](https://github.com/jacobkim9881/localization-manager#quick-start), [the third](https://github.com/jacobkim9881/localization-manager#example-adding--deleting-countries-of-langsexplain-object-in-lang_codejs)) will be not be in use as a document. So related paths and guides should be edited according to #7. After editing the guides and #7 are updated at once, users can use the repository with correct usage.

#### Problem
- If new feature #7 is applied then the guides in `README.md` are in no use.

**Comment by jacobkim9881** [comment]
@TeaBizzy Please to check this issue and give any idea.

**Comment by TeaBizzy** [comment]
Hi @jacobkim9881, do you want the documentation updated before this pull request is accepted?

Edit: I can take a look this tomorrow(Sept 20), and update them.

**Comment by jacobkim9881** [comment]
@TeaBizzy that can be one of other possible objective(I thought editing the docu as an objective). As I read the docu 3 should be edited like above. The docu guides users to update `langsExplain` directly but #7 let users update in an array indirectly. Thought adding Todos in the issue but I will wait for your update with [TeaBizzy:improve-language-selector](https://github.com/TeaBizzy/localization-manager/tree/improve-language-selector) then.

**Comment by TeaBizzy** [comment]
@jacobkim9881, friendly reminder to close this issue :smiley:

**Comment by jacobkim9881** [comment]
@TeaBizzy Thanks for the reminder. I will close this issue after mergeing [TeaBizzy:improve-language-selector](https://github.com/TeaBizzy/localization-manager/tree/improve-language-selector)!

**Comment by jacobkim9881** [comment]
@TeaBizzy I found some paths are changed on doc after #7 and [the pull request](https://github.com/TeaBizzy/localization-manager/pull/1) and I [edited doc](https://github.com/jacobkim9881/localization-manager/commit/2a85bffa5689ca0c884708d908489b56f4b12205). There was nothing to edit but I want you to double-check.

**Comment by TeaBizzy** [comment]
@jacobkim9881 I have reviewed your updated documentation. It looks accurate and up to date with your changes.

**Comment by jacobkim9881** [comment]
This issue solved by [editing document](https://github.com/jacobkim9881/localization-manager/commit/a1195da6269f7672757fe9e445fc0484462dff1b). Thanks @TeaBizzy.
